#!/bin/sh
HERE="$(dirname "$(readlink -f "${0}")")"
export QT_QPA_PLATFORMTHEME=""
export QT_STYLE_OVERRIDE=""
export LD_LIBRARY_PATH="${HERE}/_internal:${HERE}/usr/lib:${LD_LIBRARY_PATH}"
exec "${HERE}/app" "$@"
